services:
    database:
        build: ./compose-recipes/postgres
        container_name: "${NAMESPACE}-database"
        shm_size: 128mb
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=liferay
            - POSTGRES_PASSWORD=password
        healthcheck:
            interval: 5s
            retries: 50
            start_period: 30s
            test: "pg_isready -U liferay -d ${DATABASE_NAME} && grep 'STARTING_UP' /startup_log.txt"
            timeout: 5s
        ports:
            - "5433:5432"
        deploy:
            resources:
                limits:
                    memory: 1G
                reservations:
                    memory: 1G
        volumes:
            -   read_only: true
                source: postgres-dumps-volume
                target: /docker-entrypoint-initdb.d
                type: volume
            -   source: postgres-data-volume
                target: /var/lib/postgresql/data
                type: volume
volumes:
    postgres-data-volume:
    postgres-dumps-volume: