services:
    liferay:
        container_name: ${NAMESPACE}-liferay
        env_file:
            -   path: ./liferay-jvm-opts.env
                required: false
        environment:
            -   GLOWROOT_ENABLED=${GLOWROOT_ENABLED}
            -   LIFERAY_JPDA_ENABLED=true
            -   LIFERAY_DISABLE_TRIAL_LICENSE=true
            -   LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN=true
        healthcheck:
            interval: 5s
            start_period: 5m
            test: /opt/liferay/health-check.sh
            timeout: 5m
        image: ${LIFERAY_IMAGE_NAME}
        ports:
            -   "8080:8080"
            -   "11311:11311"
            -   "8000:8000"
        volumes:
            -   source: ./binds/liferay/deploy
                target: /mnt/liferay/deploy
                type: bind
            -   source: ./binds/liferay/logs/
                target: /opt/liferay/logs
                type: bind
            -   source: ./binds/liferay/reports/
                target: /opt/liferay/reports
                type: bind
            -   source: data-volume
                target: /opt/liferay/data
                type: volume
                volume:
                    subpath: container-data/liferay