jobs:
    run-source-formatter:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: "21"
            -   run: ./gradlew formatSource
name: source-formatter
on: [pull_request]